name: pathways
dependencies:
- click=6.6=py27_0
- matplotlib=1.5.1=np110py27_0
- numpy=1.10.0=py27_0
- pandas=0.17.1=np110py27_0
- pip=8.1.2=py27_0
- psycopg2=2.6.2=py27_0
- python=2.7.12=1
- pytz=2015.7=py27_0
- scikit-learn=0.17.1=np110py27_0
- scipy=0.17.0=np110py27_0
- setuptools=27.2.0=py27_0
- pip:
  - datetime==4.0.1
  - ddt=1.1.1
  - numexpr==2.6.1
  - pint==0.6
  - profilehooks==1.8.1
  - pyomo==4.2.10784
